/* ============================================================
   CONHECIMENTO AUTOLAC — base para elaboração de prompts
   Fonte: Painel de Negociação de Módulos (28 módulos) +
   Agente de Inteligência de Mercado (16 concorrentes), WMI Solutions.
   Cada módulo tem: nome, categoria, pitch (elevator) e visual
   (conceito de cena SEM TEXTO para o Gemini gerar a imagem base).
   ============================================================ */
window.AUTOLAC = {
  contexto: "Autolac é o sistema (LIS) para laboratórios de análises clínicas da WMI Solutions. Público: donos e gestores de laboratório clínico. Tom: consultivo, foco em risco/custo invisível, não em preço.",

  modulos: [
    { nome:'Migração Cloud', cat:'Licenciamento',
      pitch:'Tira o lab do risco do servidor físico e vira SaaS — acesso de qualquer ponto, backup contínuo, manutenção sem parar.',
      visual:'transição de um servidor físico antigo e empoeirado em uma sala escura para um data center moderno na nuvem, dados fluindo em linhas de luz azul e ciano, sensação de segurança e modernização' },
    { nome:'Acessos Simultâneos', cat:'Licenciamento',
      pitch:'Cobrança por acesso simultâneo, não por usuário — paga só pelo pico. Venda mais previsível da base (94% win).',
      visual:'rede de múltiplos pontos de acesso conectados a um núcleo central luminoso, nós distribuídos com conexões em ciano, ideia de escala e flexibilidade' },
    { nome:'Financeiro', cat:'Gestão',
      pitch:'Move o lab da planilha pra DRE viva. Bloqueia receita perdida em glosa via integração com atendimento e estoque.',
      visual:'dashboard financeiro holográfico flutuante com gráficos de receita ascendentes e indicadores, abstrato, sem texto legível, tons azul e ciano' },
    { nome:'Estoque', cat:'Gestão',
      pitch:'Para de perder reagente por validade e de comprar no susto. Importa XML de nota, alerta vencimento, requisição por centro de custo.',
      visual:'prateleira organizada de frascos e reagentes de laboratório com etiquetas e leitura por código, iluminação clean, controle e organização' },
    { nome:'Confere (Delta Check)', cat:'Performance',
      pitch:'Libera exames dentro dos parâmetros automaticamente — 97% menos tempo do bioquímico em conferência.',
      visual:'analisador clínico automatizado processando amostras em esteira, selo de aprovação verde brilhante, automação e velocidade, ambiente laboratorial moderno' },
    { nome:'Interlac', cat:'Performance',
      pitch:'Interfaceamento de equipamento — resultado entra no sistema sem digitação. Carro-chefe (89% win, 173 deals).',
      visual:'equipamento de análise clínica conectado por cabo de luz a um computador, resultado fluindo sem digitação, close-up tecnológico, brilho ciano' },
    { nome:'Autorização Online', cat:'Integração',
      pitch:'Tira a recepcionista do telefone com convênio (91% win). Cassi, Bradesco, IPSEMG, Unimed, etc.',
      visual:'recepção de laboratório moderna e tranquila, telefone no gancho, tela mostrando aprovação instantânea com check, ideia de processo desburocratizado' },
    { nome:'Comunicação com Apoio', cat:'Integração',
      pitch:'Integra com 11 labs de apoio (Álvaro, DB, Pardini...). Requisição automática + laudo de volta. 86% win.',
      visual:'rede de laboratórios conectados em um mapa abstrato, amostras e requisições viajando como pontos de luz entre nós, colaboração' },
    { nome:'Laudos Web', cat:'Relacionamento',
      pitch:'Paciente acessa laudo pelo portal — sem ir buscar. Reduz fluxo de recepção e papel.',
      visual:'paciente em casa acessando resultado de exame no smartphone, ambiente aconchegante e desfocado, tela com gráfico abstrato sem texto, conveniência' },
    { nome:'Kualiz Automação', cat:'Relacionamento',
      pitch:'Mensagens automáticas via WhatsApp pro paciente: laudo liberado, lembrete, aniversário, campanhas.',
      visual:'smartphone com balões de mensagem de WhatsApp estilizados saindo da tela, ícones de notificação em ciano, automação de relacionamento, sem texto legível' },
    { nome:'Kualiz Gestão', cat:'Relacionamento',
      pitch:'CRM pro WhatsApp do lab: filas, URA, BI de atendimento, monitoramento em tempo real. Pra quem tem volume.',
      visual:'central de atendimento moderna com painel de filas e indicadores em tempo real, headset, monitor com dashboard abstrato, ambiente profissional' },
    { nome:'Fila de Atendimento e Coleta', cat:'Performance',
      pitch:'Mapeia o tempo do paciente: chegada → recepção → coleta. TAT mensurável, KPI executivo pronto.',
      visual:'fluxo de pessoas em uma recepção de laboratório com linha do tempo luminosa marcando etapas, cronômetro abstrato, eficiência e medição' },
    { nome:'NFS-e', cat:'Performance',
      pitch:'Emite nota fiscal direto do atendimento — 1 clique, vai por e-mail pro paciente.',
      visual:'documento de nota fiscal eletrônico estilizado se transformando em envelope de e-mail, fluxo de 1 clique, simplicidade, brilho azul' },
    { nome:'Auditoria Pré-Faturamento', cat:'Performance',
      pitch:'Confere todas as guias antes do faturamento. Bloqueia glosa antes do convênio devolver.',
      visual:'lupa luminosa sobre uma pilha de guias/documentos com um escudo de proteção bloqueando um erro vermelho, prevenção e segurança financeira' },
    { nome:'Autolac App / BI', cat:'Gestão',
      pitch:'App pro gestor liberar laudo e ver indicadores em qualquer lugar. BI executivo + liberação mobile.',
      visual:'gestor segurando tablet com painel de indicadores executivos abstratos, em pé fora do laboratório, mobilidade e decisão, tons azul/ciano' },
    { nome:'Apoio x Apoiado', cat:'Integração',
      pitch:'Integra dois Autolacs entre si. Lab de apoio se conecta nativamente ao apoiado. Lock-in puro.',
      visual:'dois sistemas representados por dois núcleos luminosos se conectando por um elo forte de energia, integração nativa, parceria sólida' },
    { nome:'Assinatura Digital', cat:'Relacionamento',
      pitch:'Validade jurídica no laudo. Substitui assinatura física do responsável técnico — segurança e economia.',
      visual:'documento de laudo com um selo digital luminoso e assinatura eletrônica, cadeado de segurança, validade e confiança, sem texto legível' },
    { nome:'Integração Amplum', cat:'Integração',
      pitch:'Conecta Autolac ao Amplum — médico solicita exame direto e recebe laudo automático.',
      visual:'médico em consultório conectado digitalmente a um laboratório, fluxo de pedido e laudo como linhas de luz, parceria clínica-lab' },
    { nome:'Integração RNDS', cat:'Integração',
      pitch:'Envio automático de resultados notificáveis pra RNDS/SUS. Compliance regulatório sem trabalho manual.',
      visual:'mapa estilizado do Brasil com dados de saúde fluindo para uma rede nacional central, compliance e conexão pública, tons azul e ciano' },
    { nome:'Integração Hospitalar', cat:'Integração',
      pitch:'Conecta Autolac ao sistema hospitalar (SPData, Celk, Tasy...). Abre porta pra contrato hospitalar.',
      visual:'corredor hospitalar moderno desfocado com fluxo digital de dados de exames conectando lab e hospital, ambiente clínico premium' },
    { nome:'Integração SOC GED', cat:'Integração',
      pitch:'Integra com sistema de medicina do trabalho. Abre porta pra captação de clínicas SESMT.',
      visual:'ambiente de medicina ocupacional, capacete e prancheta digital desfocados, exames ocupacionais fluindo digitalmente, saúde do trabalhador' },
    { nome:'Integração Vector', cat:'Integração',
      pitch:'Fluxo digital com clínicas que usam Vector. Pequeno volume, alto lock-in.',
      visual:'duas plataformas digitais se acoplando por engrenagens de luz, fluxo contínuo, integração técnica, abstrato azul/ciano' },
    { nome:'API Autolac', cat:'Integração',
      pitch:'Endpoints pra integrações customizadas. Pra labs com TI ou parceiro de desenvolvimento.',
      visual:'representação abstrata de código e endpoints como blocos de luz conectados, desenvolvedor, integração de sistemas, fundo escuro tecnológico' },
    { nome:'ALLIS', cat:'Relacionamento',
      pitch:'App do paciente — histórico e localização do lab mais próximo. Diferencial de retenção mobile.',
      visual:'smartphone com app de saúde mostrando mapa e histórico em ícones abstratos, mão segurando, conveniência mobile, sem texto legível' },
    { nome:'ANIMALLIS', cat:'Relacionamento',
      pitch:'Plataforma pra veterinários/clínicas — pet com cadastro próprio. Abre o nicho veterinário.',
      visual:'cachorro e gato saudáveis em ambiente clean de clínica veterinária, smartphone com app pet desfocado, nicho veterinário, tons azul/ciano acolhedor' },
    { nome:'Pesquisa de Satisfação', cat:'Relacionamento',
      pitch:'CSAT integrado pós-atendimento — mede experiência real e fortalece marca com dado.',
      visual:'tela com estrelas de avaliação brilhantes e medidor de satisfação ascendente, paciente sorrindo desfocado ao fundo, feedback positivo' },
    { nome:'Plataforma Aprenda', cat:'Performance',
      pitch:'Capacitação exclusiva pra clientes Autolac — cursos em análises clínicas, BPL, qualidade.',
      visual:'ambiente de e-learning, tela de curso online com play e progresso abstratos, equipe de laboratório aprendendo, capacitação' },
    { nome:'Novos Módulos Autolac 10.0', cat:'Licenciamento',
      pitch:'Próxima geração — layout moderno 100% browser, gratuito pro cliente cloud. A evolução da plataforma.',
      visual:'interface de software ultra-moderna flutuando no navegador, cards e gráficos limpos em glassmorphism azul/ciano, evolução e futuro, SEM texto legível' }
  ],

  // Concorrentes mapeados no battlecard (para campanhas de conquista/comparação)
  concorrentes: ['AB Sistemas','Concent','EasyLab','Emerald','Hotsoft','Jallis','Klingo','LabSys','Liga Sistemas','Manlab','Pixeon','Shift','Techmobil','Unilab','Wise-Lab','Worklab'],

  // Princípio de copy (do painel): NUNCA vender por preço. Vender o custo invisível de NÃO ter o módulo
  // (horas-equipe, erro humano, retrabalho, glosa, no-show, paciente perdido).
  principioCopy: 'Não vender por preço. Mostrar o custo invisível de não ter a solução: horas da equipe, erro humano, retrabalho, glosa, paciente perdido.',

  // Palavras-chave que mapeiam linguagem natural do briefing -> módulo
  aliases: {
    'Migração Cloud': ['servidor fisico','servidor proprio','sem servidor','nuvem','cloud','backup','data center','migracao','autolac 10','autolac v10','versao 10','100% browser','navegador'],
    'Acessos Simultâneos': ['acesso simultaneo','licenca','usuario','escalavel'],
    'Financeiro': ['financeiro','dre','fluxo de caixa','receita','glosa','contabil'],
    'Estoque': ['estoque','reagente','validade','xml de nota','compra'],
    'Confere (Delta Check)': ['delta check','liberacao automatica','conferencia','libera exame','bioquimico'],
    'Interlac': ['interlac','interfaceamento','equipamento','sem digitacao','analisador'],
    'Autorização Online': ['convenio','autorizacao','recepcionista','telefone','unimed','bradesco','elegibilidade'],
    'Comunicação com Apoio': ['lab de apoio','apoio','pardini','alvaro','requisicao'],
    'Laudos Web': ['laudo online','laudo no celular','laudo pelo site','resultado online','portal do paciente','exame pelo celular','liberacao de exame','buscar resultado'],
    'Kualiz Automação': ['whatsapp automatico','mensagem automatica','lembrete','aniversario','notificacao','laudo liberado','campanha','outubro rosa'],
    'Kualiz Gestão': ['crm','fila de whatsapp','ura','central de atendimento','monitoramento'],
    'Fila de Atendimento e Coleta': ['fila','tempo de espera','tat','coleta','recepcao'],
    'NFS-e': ['nota fiscal','nfse','nfs-e','emissao de nota'],
    'Auditoria Pré-Faturamento': ['faturamento','guia','glosa','auditoria','convenio devolve'],
    'Autolac App / BI': ['app do gestor','indicadores','dashboard','bi','gestao mobile','liberar laudo'],
    'Apoio x Apoiado': ['apoio x apoiado','dois labs','integrar autolac'],
    'Assinatura Digital': ['assinatura digital','validade juridica','assinatura','responsavel tecnico'],
    'Integração Amplum': ['amplum'],
    'Integração RNDS': ['rnds','sus','notificavel','covid','compliance'],
    'Integração Hospitalar': ['hospital','tasy','spdata','celk','contrato hospitalar'],
    'Integração SOC GED': ['medicina do trabalho','sesmt','ocupacional','soc'],
    'Integração Vector': ['vector'],
    'API Autolac': ['api','endpoint','integracao customizada'],
    'ALLIS': ['app do paciente','allis','historico do paciente'],
    'ANIMALLIS': ['veterinario','pet','animal','animallis'],
    'Pesquisa de Satisfação': ['satisfacao','csat','avaliacao','feedback','nps'],
    'Plataforma Aprenda': ['capacitacao','curso','treinamento','aprenda','bpl'],
    'Novos Módulos Autolac 10.0': ['autolac 10','autolac v10','versao 10','nova versao','100% browser']
  }
};
